# **Disciplina: DS-006**
**Aula: 02**

Topicos abordados:

* Agrupamentos de dados
* Manipulação Geometrica
* Latitude e longitude
* Obtendo latitude e longitude de shape
* Plot de mapa com pontos

In [ ]:
"""
Bibliotecas a serem utilizadas
"""
import pandas as pd

Dados relacionados a **Febre Amarela em humanos e primatas não-humanos - 1994 a 2023**

Dataset a ser utilizado foi obtido em: https://opendatasus.saude.gov.br/dataset/febre-amarela-em-humanos-e-primatas-nao-humanos

Descrição dos dataset: https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/Febre+Amarela/Dicionario+de+variaveis.pdf

In [ ]:
url = 'https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/Febre+Amarela/fa_casoshumanos_1994-2023.csv'
df = pd.read_csv(url,encoding = "ISO-8859-1", sep=';')

**Conhecendo o dataset**

In [ ]:
df.head()
#Descrição dos dataset: https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/Febre+Amarela/Dicionario+de+variaveis.pdf

,ID,MACRORREG_LPI,COD_UF_LPI,UF_LPI,COD_MUN_LPI,MUN_LPI,SEXO,IDADE,DT_IS,SE_IS,MES_IS,ANO_IS,MONITORAMENTO_IS,OBITO,DT_OBITO
0,1,N,14,RR,140005.0,ALTO ALEGRE,M,NaN,29/11/1994,48.0,11.0,1994,1994/1995,SIM,01/12/1994
1,2,N,14,RR,140045.0,PACARAIMA,M,19,19/02/1995,8.0,2.0,1995,1994/1995,NÃO,NaN
2,3,NE,21,MA,210060.0,AMARANTE DO MARANHÃO,M,32,01/04/1995,13.0,4.0,1995,1994/1995,IGN,NaN
3,4,NE,21,MA,210060.0,AMARANTE DO MARANHÃO,M,33,03/04/1995,14.0,4.0,1995,1994/1995,SIM,09/04/1995
4,5,N,15,PA,150270.0,CONCEIÇÃO DO ARAGUAIA,M,26,12/04/1995,15.0,4.0,1995,1994/1995,SIM,20/04/1995

In [ ]:
#Substituindo o NaN e valores vazios por 0 e removendo valores como string

# Replace NaN and empty values with 0
df["IDADE"] = df["IDADE"].fillna(0)
df["IDADE"] = df["IDADE"].replace('', 0)

# Remove string values (if any) and convert to numeric
df["IDADE"] = pd.to_numeric(df["IDADE"], errors='coerce').fillna(0).astype(int)
df["IDADE"].mean()

42.53901734104046

In [ ]:
# Ordenando o dataframe
df_ordenado = df.sort_values('UF_LPI')
df_ordenado.head()

# Conhecendo os códigos do municipios: https://www.ibge.gov.br/explica/codigos-dos-municipios.php

,ID,MACRORREG_LPI,COD_UF_LPI,UF_LPI,COD_MUN_LPI,MUN_LPI,SEXO,IDADE,DT_IS,SE_IS,MES_IS,ANO_IS,MONITORAMENTO_IS,OBITO,DT_OBITO
2735,2736,N,12,AC,120001.0,ACRELÂNDIA,M,16,30/01/2020,5.0,1.0,2020,2019/2020,SIM,10/02/2020
216,217,N,12,AC,120038.0,PLÁCIDO DE CASTRO,M,21,29/06/2000,26.0,6.0,2000,1999/2000,NÃO,NaN
336,337,N,13,AM,130440.0,URUCURITUBA,F,16,13/05/2003,20.0,5.0,2003,2001/2002,NÃO,NaN
28,29,N,13,AM,130353.0,PRESIDENTE FIGUEIREDO,F,17,28/02/1998,8.0,2.0,1998,1997/1998,NÃO,NaN
2727,2728,N,13,AM,130130.0,CODAJÁS,M,21,28/02/2019,9.0,2.0,2019,2018/2019,NÃO,NaN

In [ ]:
"""
Seleção de colunas para manipulação dos dados
Criando um novo data frame usando df_ordenado que contenha as colunas:
UF_LPI, MUN_LPI, SEXO, IDADE, ANO_IS, OBITO e redefinindo o index do data frame
"""

novo_df = df_ordenado[['UF_LPI', 'MUN_LPI', 'SEXO', 'IDADE', 'ANO_IS', 'OBITO']].reset_index(drop=True)
novo_df.head()

  UF_LPI                MUN_LPI SEXO  IDADE  ANO_IS OBITO
0     AC             ACRELÂNDIA    M     16    2020   SIM
1     AC      PLÁCIDO DE CASTRO    M     21    2000   NÃO
2     AM            URUCURITUBA    F     16    2003   NÃO
3     AM  PRESIDENTE FIGUEIREDO    F     17    1998   NÃO
4     AM                CODAJÁS    M     21    2019   NÃO

In [ ]:
# Convertendo para lower case a coluna MUN_LPI para padronizar a comparação

novo_df['MUN_LPI'] = novo_df['MUN_LPI'].str.lower()
novo_df['MUN_LPI']

0                  acrelândia
1           plácido de castro
2                 urucurituba
3       presidente figueiredo
4                     codajás
                ...
2763                    almas
2764            campos lindos
2765                  arraias
2766            campos lindos
2767            campos lindos
Name: MUN_LPI, Length: 2768, dtype: object

In [ ]:
# Conhecendo a biblioteca GEOBR: https://ipeagit.github.io/geobr/articles/python-intro/py-intro-to-geobr.html
!pip install geobr

Requirement already satisfied: geobr in /usr/local/lib/python3.10/dist-packages (0.2.1)
Requirement already satisfied: geopandas<0.15.0,>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from geobr) (0.14.4)
Requirement already satisfied: lxml<6.0.0,>=5.1.0 in /usr/local/lib/python3.10/dist-packages (from geobr) (5.3.0)
Requirement already satisfied: requests<3.0.0,>=2.25.1 in /usr/local/lib/python3.10/dist-packages (from geobr) (2.32.3)
Requirement already satisfied: shapely<2.0.0,>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from geobr) (1.8.5.post1)
Requirement already satisfied: fiona>=1.8.21 in /usr/local/lib/python3.10/dist-packages (from geopandas<0.15.0,>=0.14.0->geobr) (1.10.0)
Requirement already satisfied: numpy>=1.22 in /usr/local/lib/python3.10/dist-packages (from geopandas<0.15.0,>=0.14.0->geobr) (1.26.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from geopandas<0.15.0,>=0.14.0->geobr) (24.1)
Requirement already satisfied: pandas>=1.4.0 in /usr/local/lib/python3.10/dist-packages (from geopandas<0.15.0,>=0.14.0->geobr) (2.1.4)
Requirement already satisfied: pyproj>=3.3.0 in /usr/local/lib/python3.10/dist-packages (from geopandas<0.15.0,>=0.14.0->geobr) (3.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.25.1->geobr) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.25.1->geobr) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.25.1->geobr) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.25.1->geobr) (2024.8.30)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.21->geopandas<0.15.0,>=0.14.0->geobr) (24.2.0)
Requirement already satisfied: click~=8.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.21->geopandas<0.15.0,>=0.14.0->geobr) (8.1.7)
Requirement already satisfied: click-plugins>=1.0 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.21->geopandas<0.15.0,>=0.14.0->geobr) (1.1.1)
Requirement already satisfied: cligj>=0.5 in /usr/local/lib/python3.10/dist-packages (from fiona>=1.8.21->geopandas<0.15.0,>=0.14.0->geobr) (0.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->geopandas<0.15.0,>=0.14.0->geobr) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->geopandas<0.15.0,>=0.14.0->geobr) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.4.0->geopandas<0.15.0,>=0.14.0->geobr) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas<0.15.0,>=0.14.0->geobr) (1.16.0)

In [ ]:
import geobr

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

---
# **Início da aula 002**

---

In [ ]:
# Obtendo os municipios do brasil
municipalities  = geobr.read_municipality()

In [ ]:
municipalities.shape

(5567, 5)

In [ ]:
municipalities.head()

,code_muni,name_muni,code_state,abbrev_state,geometry
0,1100015.0,Alta Floresta D'oeste,11.0,RO,"MULTIPOLYGON (((-62.24620 -11.90149, -62.24151..."
1,1100023.0,Ariquemes,11.0,RO,"MULTIPOLYGON (((-63.13712 -9.78413, -63.09013 ..."
2,1100031.0,Cabixi,11.0,RO,"MULTIPOLYGON (((-60.52408 -13.32137, -60.37161..."
3,1100049.0,Cacoal,11.0,RO,"MULTIPOLYGON (((-61.42679 -11.11376, -61.42900..."
4,1100056.0,Cerejeiras,11.0,RO,"MULTIPOLYGON (((-61.41347 -13.23417, -61.42603..."

# **Entendo centroids**

In [ ]:
import geopandas as gpd

In [ ]:
from shapely.geometry import Polygon, LineString, Point

In [ ]:
# TODO: Create a geodataframe usando diferentes poligonos
s = gpd.GeoSeries(
    [
        Polygon([ (0.0, 0.0), (1.1, 1.1), (1,0) ]),
        LineString([(0.0, 0.0), (1.1, 1.1), (1,0)]),
        Point(0,0)])

In [ ]:
# TODO: Apresente o geodataframe

In [ ]:
# TODO: Apresente os centroid dos poligonos

**Voltando para a análise**

In [ ]:
# Criar um data frame que contenha para cada municipio a latidude e longitude

# Extraindo latitude e longitude
municipalities_lat_long = municipalities[['name_muni', 'geometry', 'abbrev_state']].copy()
municipalities_lat_long['name_muni'] = municipalities_lat_long['name_muni'].str.lower()

# Extraindo latitude e longitude da coluna 'geometry'
municipalities_lat_long['latitude'] = municipalities_lat_long['geometry'].apply(
    lambda point: point.centroid.y
    )

# TODO: Extraindo longitude da coluna 'geometry'
municipalities_lat_long['longitude'] = municipalities_lat_long['geometry'].apply(
    lambda point: point.centroid.x
    )

# TODO: Removendo a coluna 'geometry'
municipalities_lat_long = municipalities_lat_long.drop(columns=['geometry'])


# Display the resulting DataFrame
municipalities_lat_long.head()

               name_muni abbrev_state   latitude  longitude
0  alta floresta d'oeste           RO -12.470168 -62.274672
1              ariquemes           RO  -9.951899 -62.957181
2                 cabixi           RO -13.474891 -60.639857
3                 cacoal           RO -11.301229 -61.324749
4             cerejeiras           RO -13.203513 -61.260921

# Falando sobre CRS - Coordinate Reference System

In [ ]:
# https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.crs.html
# https://spatialreference.org/
# https://epsg.io/4674
municipalities.crs

<Geographic 2D CRS: EPSG:4674>
Name: SIRGAS 2000
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: Latin America - Central America and South America - onshore and offshore. Brazil - onshore and offshore.
- bounds: (-122.19, -59.87, -25.28, 32.72)
Datum: Sistema de Referencia Geocentrico para las AmericaS 2000
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

**Usando CRS para organizar o shape**

In [ ]:
# https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoDataFrame.html
gdf = gpd.GeoDataFrame(municipalities) # versão completa

In [ ]:
gdf.head()

,code_muni,name_muni,code_state,abbrev_state,geometry
0,1100015.0,Alta Floresta D'oeste,11.0,RO,"MULTIPOLYGON (((-62.24620 -11.90149, -62.24151..."
1,1100023.0,Ariquemes,11.0,RO,"MULTIPOLYGON (((-63.13712 -9.78413, -63.09013 ..."
2,1100031.0,Cabixi,11.0,RO,"MULTIPOLYGON (((-60.52408 -13.32137, -60.37161..."
3,1100049.0,Cacoal,11.0,RO,"MULTIPOLYGON (((-61.42679 -11.11376, -61.42900..."
4,1100056.0,Cerejeiras,11.0,RO,"MULTIPOLYGON (((-61.41347 -13.23417, -61.42603..."

In [ ]:
# TODO: Obter o crs do gdf
gdf.crs

<Geographic 2D CRS: EPSG:4674>
Name: SIRGAS 2000
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: Latin America - Central America and South America - onshore and offshore. Brazil - onshore and offshore.
- bounds: (-122.19, -59.87, -25.28, 32.72)
Datum: Sistema de Referencia Geocentrico para las AmericaS 2000
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [ ]:
# https://epsg.io/3857
# Observar as coordenadas em geometry
# TODO: Alterar o CRS de gdf para 3857

# Voltando a nossa análise dos dados

In [ ]:
"""
Usando municipalities_lat_long compara a coluna name_muni com a coluna MUN_LPI
em novo_df, caso verdade adicione as colunas latitude e longitude de
municipalities_lat_long em novo_df
"""
for index, row in municipalities_lat_long.iterrows():
    matching_rows = novo_df[(novo_df['MUN_LPI'] == row['name_muni']) & (novo_df['UF_LPI'] == row['abbrev_state'])]

    if not matching_rows.empty:
        novo_df.loc[matching_rows.index, 'latitude'] = row['latitude']
        # TODO: fazer a inserção de longitude
        novo_df.loc[matching_rows.index, 'longitude'] = row['longitude']
novo_df.head()

,UF_LPI,MUN_LPI,SEXO,IDADE,ANO_IS,OBITO,latitude,longitude
0,AC,acrelândia,M,16,2020,SIM,-9.933663,-66.950435
1,AC,plácido de castro,M,21,2000,NÃO,-10.248878,-67.339865
2,AM,urucurituba,F,16,2003,NÃO,-2.812398,-57.770333
3,AM,presidente figueiredo,F,17,1998,NÃO,-1.372441,-59.988939
4,AM,codajás,M,21,2019,NÃO,-3.289089,-62.972878

In [ ]:
import plotly.express as px

In [ ]:
"""
Plotar os casos de febre amarela no mapa do brasil com localidades
"""
# Criando o mapa
fig = px.scatter_geo(novo_df,
                     lat='latitude',
                     lon='longitude',
                     hover_name='MUN_LPI',
                     title='Casos de Febre no Brasil',
                     color_discrete_sequence=['red']
                     )

# Atualização a layer do mapa
fig.update_layout(geo=dict(
        showland=True,
        landcolor="rgb(212, 212, 212)",
        subunitcolor="rgb(255, 255, 255)",
        countrycolor="rgb(255, 255, 255)",
        showlakes=True,
        lakecolor="rgb(255, 255, 255)",
        showsubunits=True,
        showcountries=True,
        resolution=50,
        scope='south america',  # Focus on South America
        projection=dict(
            type='mercator',  # Use Mercator projection
            scale=2.5  # Adjust scale as needed
        )
    ),
    margin={"r":0,"t":30,"l":0,"b":0}
)


fig.show()

# Focando no estado de Roraima

In [ ]:
# TODO: Filtra o DataFrame para incluir apenas linhas onde 'UF_LPI' é igual a 'RR'


# Exibe o novo DataFrame
novo_df_rr = novo_df[novo_df['UF_LPI'] == 'RR']
novo_df_rr

     UF_LPI       MUN_LPI SEXO  IDADE  ANO_IS OBITO  latitude  longitude
1986     RR   alto alegre    M      0    1994   SIM  3.078285 -62.755527
1987     RR  rorainópolis    M     38    2023   SIM  0.037840 -61.010437
1988     RR   alto alegre    F     54    1998   NÃO  3.078285 -62.755527
1989     RR       caroebe    M     15    2007   SIM  0.914696 -59.338126
1990     RR       mucajaí    M     26    2005   SIM  2.513322 -61.995674
1991     RR   alto alegre    M     15    2002   SIM  3.078285 -62.755527
1992     RR       mucajaí    M     16    2002   NÃO  2.513322 -61.995674
1993     RR      uiramutã    M     19    1999   SIM  4.684050 -60.280825
1994     RR   alto alegre    M     20    1998   SIM  3.078285 -62.755527
1995     RR       mucajaí    M     20    1998   SIM  2.513322 -61.995674
1996     RR   alto alegre    M     22    1998   SIM  3.078285 -62.755527
1997     RR       iracema    F     30    1998   SIM  2.190457 -62.448853
1998     RR         cantá    M     26    1999   NÃO  2.272821 -60.542225
1999     RR   alto alegre    M     26    1998   NÃO  3.078285 -62.755527
2000     RR     pacaraima    M     19    1995   NÃO  4.168709 -60.839456
2001     RR         cantá    F     28    2001   SIM  2.272821 -60.542225
2002     RR   alto alegre    M     20    1998   NÃO  3.078285 -62.755527
2003     RR      uiramutã    M     27    1999   SIM  4.684050 -60.280825

In [ ]:
# Criando uma mapa usando novo_df_rr contendo um ponto em vermelho para cada
# coluna latitude e longitude

"""
plotar o brasil com localidades da doença
"""

import plotly.express as px

# Create the map
fig = px.scatter_geo(novo_df_rr,
                     lat='latitude',
                     lon='longitude',
                     hover_name='MUN_LPI',  # Display municipality name on hover
                     title='Casos de Febre Amarela em Roraima',
                     color_discrete_sequence=['red'])  # Set marker color to red

# Update map layout for better visualization
fig.update_layout(geo=dict(
        showland=True,
        landcolor="rgb(212, 212, 212)",
        subunitcolor="rgb(255, 255, 255)",
        countrycolor="rgb(255, 255, 255)",
        showlakes=True,
        lakecolor="rgb(255, 255, 255)",
        showsubunits=True,
        showcountries=True,
        resolution=50,
        scope='south america',  # Focus on South America
        center=dict(lat=novo_df_rr['latitude'].mean(), lon=novo_df_rr['longitude'].mean())  # Center on Roraima
    ),
    margin={"r":0,"t":30,"l":0,"b":0}
)

fig.show()

# **Analisado os dados dos resultados**

In [ ]:
novo_df_rr.head()

     UF_LPI       MUN_LPI SEXO  IDADE  ANO_IS OBITO  latitude  longitude
1986     RR   alto alegre    M      0    1994   SIM  3.078285 -62.755527
1987     RR  rorainópolis    M     38    2023   SIM  0.037840 -61.010437
1988     RR   alto alegre    F     54    1998   NÃO  3.078285 -62.755527
1989     RR       caroebe    M     15    2007   SIM  0.914696 -59.338126
1990     RR       mucajaí    M     26    2005   SIM  2.513322 -61.995674

In [ ]:
# Obtenha a latitude e longitude do valor iracema na coluna MUN_LPI

iracema_row = novo_df_rr[novo_df_rr['MUN_LPI'] == 'iracema']

# TODO: Extraindo os valores de latitude e longitude de iracema
latitude_iracema = iracema_row['latitude'].values[0]
longitude_iracema = iracema_row['longitude'].values[0]

print(f"Latitude de Iracema: {latitude_iracema}")
print(f"Longitude de Iracema: {longitude_iracema}")

Latitude de Iracema: 2.1904568519099694
Longitude de Iracema: -62.44885316912735

**Identificando possível erro**
- Ema, Iracema - CE no google maps

In [ ]:
novo_df_sp = novo_df[novo_df['UF_LPI'] == 'SP']
fig = px.scatter_geo(novo_df_sp,
                     lat='latitude',
                     lon='longitude',
                     hover_name='MUN_LPI',
                     title='Casos de Febre Amarela em São Paulo',
                     color_discrete_sequence=['red'])
fig.update_layout(geo=dict(
        showland=True,
        landcolor="rgb(212, 212, 212)",
        subunitcolor="rgb(255, 255, 255)",
        countrycolor="rgb(255, 255, 255)",
        showlakes=True,
        lakecolor="rgb(255, 255, 255)",
        showsubunits=True,
        showcountries=True,
        resolution=50,
        scope='south america',
        center=dict(lat=novo_df_sp['latitude'].mean(), lon=novo_df_sp['longitude'].mean())
    ),
    margin={"r":0,"t":30,"l":0,"b":0}
)

fig.show()

---
# FIM aula 02
---