***
# <font color=green size=10>**1ª ENTREGA DO PROJETO DATA SCIENCE APLICADO À SAÚDE**</font>
***

**>> Nome completo dos integrantes da equipe**
- Fernando Souza Rodrigues
- Kelvin Araújo Ferreira


**>> Tema do projeto**

*Análise do dados nutricionais em comunidades rurais e urbanas em Roraima Durante a pândemia de Covid-19.*

*Quais foram as diferenças nos índices nutricionais (como IMC) entre comunidades rurais e urbanas em Roraima durante a pandemia? Isso pode ajudar a identificar desigualdades nutricionais para embasar políticas públicas de saúde.*


**>> Banco de dados consultado**

*Sistema de Vigilância Alimentar e Nutricional (SISVAN). [link do banco de dados](https://basedosdados.org/dataset/d0b61e1c-2ff2-43e7-b32f-5a054ba9b688?table=6e763e07-9b83-487e-9135-fca7872b1f16).*


**>> Banco de dados utilizado**

[link do banco de dados pré-processoado](https://drive.google.com/file/d/1-8FE24TE5t1PBCqHtFTn85_7CurTvq2z/view?usp=sharing)

## <font color=green size=6>**Desenvolvimento do projeto**</font>

**>> Problema a ser solucionado**

*Pretendemos estudar os dados de IMC dos municípios de Roraima...*

### **01. Importação de bibliotecas necessárias para o projeto.**

In [75]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import plotly
from google.colab import drive

### **02. Importação do banco de dados original.**

In [76]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [77]:
df = pd.read_csv('/content/Dados_brasil.csv')
df.sample(5)

,ano,mes,sigla_uf,sigla_uf_nome,id_municipio,id_municipio_nome,acompanhamento,id_individuo,idade,sexo,...,imc_gestacional,estado_nutricional_peso_idade_crianca,estado_nutricional_peso_altura_crianca,estado_nutricional_altura_idade_crianca,estado_nutricional_imc_idade_crianca,estado_nutricional_altura_idade_adolescente,estado_nutricional_imc_idade_adolescente,estado_nutricional_adulto,estado_nutricional_idoso,estado_nutricional_gestantes
3720,2018,11,GO,Goiás,521030,NaN,29CF8390BFB26C4FDEBA4891B11FE930C726F711,9C60004299B163903C37613D5A2771FCC77145F1,65,M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sobrepeso,NaN
2113,2017,9,MT,Mato Grosso,510345,NaN,659BC04EC211F36816E7A0D021C6596F9407B40A,4C105E5C6F37E1F3DCFED6F50D2CF89F3378A87E,12,M,...,NaN,NaN,NaN,NaN,NaN,Estatura adequada para a idade,Eutrofia,NaN,NaN,NaN
4834,2018,4,AM,Amazonas,130310,NaN,EB04664FA75FC3D2482E83B08B44D7E7AADA1103,3E89713762B94249CE7BF9C70137371ACC230D9B,11,M,...,NaN,NaN,NaN,NaN,NaN,Estatura adequada para a idade,Sobrepeso,NaN,NaN,NaN
8638,2014,10,MT,Mato Grosso,510880,NaN,622C9F041E891F707DC3317FC3162117FA3E0A2B,3E5645EC65A4CF1A83F84FDB4F2ABBB209CB42D6,39,M,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sobrepeso,NaN,NaN
2169,2017,9,MT,Mato Grosso,510794,NaN,AD2E7ED027E9E50B34CCA1649B267469046E411C,B74CED907DD49409400021D8909B3593CA61290C,56,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adequado ou eutrófico,NaN,NaN

### **03. Pré-processamento dos dados para produzir o banco de dados para análise exploratória.**

####Traduzindo os códigos de município de Roraima

In [78]:
# Recomendamos que a equipe divida em várias células de código cada etapa do
# processamento e que utilize comentários para descrever cada etapa.
# Tabela com os códigos e nomes dos municípios de Roraima
tabela_roraima = pd.DataFrame({
    "CODIGO_IBGE": [
        140002, #1400027 - Amajari
        140005, #1400050 - Alto Alegre
        140010, #1400100 - Boa Vista
        140045, #1400456 - Pacaraima
        140015, #1400159 - Bonfim
        140017, #1400175 - Cantá
        140040, #1400407 - Normandia
        140070, #1400704 - Uiramutã
        140020, #1400209 - Caracaraí
        140028, #1400282 - Iracema
        140030, #1400308 - Mucajaí
        140023, #1400233 - Caroebe
        140047, #1400472 - Rorainópolis
        140050, #140050 - São João da Baliza
        140060 #1400605 - São Luiz
    ],
    "MUNICIPIO": [
        "Amajari", "Alto Alegre", "Boa Vista", "Pacaraima", "Bonfim", "Cantá", "Normandia",
        "Uiramutã", "Caracaraí", "Iracema", "Mucajaí", "Caroebe", "Rorainópolis",
        "São João da Baliza", "São Luiz"
    ]
})

# Criar um dicionário para mapear os códigos aos nomes dos municípios
mapeamento = dict(zip(tabela_roraima["CODIGO_IBGE"], tabela_roraima["MUNICIPIO"]))

# Criar a nova coluna com os nomes dos municípios usando o mapeamento
df["nome_municipio"] = df["id_municipio"].map(mapeamento)

# Exibir o DataFrame atualizado
df.sample(5)

,ano,mes,sigla_uf,sigla_uf_nome,id_municipio,id_municipio_nome,acompanhamento,id_individuo,idade,sexo,...,estado_nutricional_peso_idade_crianca,estado_nutricional_peso_altura_crianca,estado_nutricional_altura_idade_crianca,estado_nutricional_imc_idade_crianca,estado_nutricional_altura_idade_adolescente,estado_nutricional_imc_idade_adolescente,estado_nutricional_adulto,estado_nutricional_idoso,estado_nutricional_gestantes,nome_municipio
6144,2018,5,SC,Santa Catarina,420420,NaN,24C9BE690C3F39E4AE11356B23CEE4477D51CA9E,53E425436BE09EF820C17F2440FB6D20B75CB8CB,7,M,...,Peso adequado para idade,NaN,Estatura adequada para a idade,Eutrofia,NaN,NaN,NaN,NaN,NaN,NaN
5970,2018,5,SC,Santa Catarina,420420,NaN,8DC99E7FF016BBF742BAE92B57984DABDFAA3817,9C3B54ECFF175B2B1D6A44DE34EEDB6D5C5DB3B4,1,F,...,Peso adequado para idade,Peso Adequado ou Eutrofico,Estatura adequada para a idade,Eutrofia,NaN,NaN,NaN,NaN,NaN,NaN
7179,2013,11,AL,Alagoas,270670,NaN,CFBE3A1D1EB33E29A14102A64E27A3AC271CA36E,3A432E4F8B9C06573EB56B4CB5758B7A9DDA091F,20,F,...,NaN,NaN,NaN,NaN,NaN,NaN,Adequado ou eutrófico,NaN,NaN,NaN
8696,2014,10,MT,Mato Grosso,510710,NaN,519EDC2CB5C890FA17D61599ADC0A13C9E725B16,7C6B505CBE5023BB2B506FA691C3D127D79364E2,17,F,...,NaN,NaN,NaN,NaN,Estatura adequada para a idade,Risco de sobrepeso,NaN,NaN,NaN,NaN
4468,2019,6,SC,Santa Catarina,421500,NaN,8466F7D10B3C8B85B66900C41F207CC92E1D7330,9B1615E8DE3C5730EACEDA32DB4D1790A6FBB34A,34,F,...,NaN,NaN,NaN,NaN,NaN,NaN,Adequado ou eutrófico,NaN,NaN,NaN

####Removendo colunas

In [79]:
# Removendo temporáriamente as colunas relacionadas aos municipios so pra ter de onde começar o começo.
# Depois voltar fazendo os filtros dos outros municipios
del df['id_municipio']
del df['id_municipio_nome']
# -----------------------------------
del df['acompanhamento']
del df['povo_comunidade']
del df['id_individuo']
del df['data_acompanhamento']
del df['estado_nutricional_peso_idade_crianca']
del df['estado_nutricional_peso_altura_crianca']
del df['estado_nutricional_altura_idade_crianca']
del df['estado_nutricional_imc_idade_crianca']
del df['estado_nutricional_altura_idade_adolescente']
del df['estado_nutricional_imc_idade_adolescente']
del df['estado_nutricional_adulto']
del df['estado_nutricional_idoso']
del df['estado_nutricional_gestantes']
del df['nome_municipio']
del df['imc_gestacional']

df

,ano,mes,sigla_uf,sigla_uf_nome,idade,sexo,raca_cor,escolaridade,peso,altura,imc
0,2013,8,AP,Amapá,30,F,Parda,Ensino fundamental 5ª a 8ª séries,75.7,1.65,27.81
1,2013,8,AP,Amapá,2,F,Parda,Creche,9.2,75.00,16.36
2,2013,8,AP,Amapá,3,M,Parda,Nenhum,15.6,100.00,15.60
3,2013,8,AP,Amapá,3,F,Branca,Creche,13.9,88.00,17.95
4,2013,8,AP,Amapá,4,M,Branca,Ensino fundamental 5ª a 8ª séries,19.1,105.00,17.32
...,...,...,...,...,...,...,...,...,...,...,...
9995,2014,10,GO,Goiás,3,F,Parda,Sem informação,12.4,90.00,15.31
9996,2014,10,GO,Goiás,5,M,Branca,Creche,18.7,115.00,14.14
9997,2014,10,GO,Goiás,5,F,Parda,Pré-escola (exceto ca),18.2,112.00,14.51
9998,2014,10,GO,Goiás,6,M,Branca,Pré-escola (exceto ca),21.1,114.00,16.24
9999,2014,10,GO,Goiás,7,F,Parda,Creche,22.8,1.27,14.14

####Contagem de valores de cada ano

In [80]:
contagem_ano = df['ano'].value_counts()

print(contagem_ano)

ano
2018    2773
2014    1535
2013    1519
2019    1411
2015    1117
2017     578
2020     332
2016     326
2012     192
2022     141
2021      75
2011       1
Name: count, dtype: int64

####Exploração Inicial dos Dados Analise o conteúdo do DataFrame para entender os dados disponíveis:

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ano            10000 non-null  int64
 1   mes            10000 non-null  int64
 2   sigla_uf       10000 non-null  object
 3   sigla_uf_nome  10000 non-null  object
 4   idade          10000 non-null  int64
 5   sexo           10000 non-null  object
 6   raca_cor       10000 non-null  object
 7   escolaridade   10000 non-null  object
 8   peso           10000 non-null  float64
 9   altura         10000 non-null  float64
 10  imc            10000 non-null  float64
dtypes: float64(3), int64(3), object(5)
memory usage: 859.5+ KB

In [82]:
df.describe()

,ano,mes,idade,peso,altura,imc
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2016.338900,7.983600,21.701100,45.582863,91.219256,22.578578
std,2.439558,3.022821,20.167013,26.878470,62.315685,13.878457
min,2011.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,2014.000000,6.000000,4.000000,18.000000,1.710000,16.500000
50%,2017.000000,9.000000,16.000000,49.600000,104.000000,20.810000
75%,2018.000000,10.000000,34.000000,66.000000,151.000000,26.020000
max,2022.000000,12.000000,102.000000,205.000000,245.000000,660.160000

####Tratar Dados Faltantes ou Inconsistentes - Verificando se há valores ausentes e trate-os adequadamente:

In [83]:
# Verificar valores nulos
print(df.isnull().sum())

# Tratar valores nulos na coluna 'imc', por exemplo, preenchendo com a mediana
df['imc'] = df['imc'].fillna(df['imc'].median())

ano              0
mes              0
sigla_uf         0
sigla_uf_nome    0
idade            0
sexo             0
raca_cor         0
escolaridade     0
peso             0
altura           0
imc              0
dtype: int64

In [84]:
# Verificar valores nulos
print(df.isnull().sum())

# Tratar valores nulos na coluna 'imc', por exemplo, preenchendo com a mediana
df['imc'] = df['imc'].fillna(df['imc'].median())

ano              0
mes              0
sigla_uf         0
sigla_uf_nome    0
idade            0
sexo             0
raca_cor         0
escolaridade     0
peso             0
altura           0
imc              0
dtype: int64

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ano            10000 non-null  int64
 1   mes            10000 non-null  int64
 2   sigla_uf       10000 non-null  object
 3   sigla_uf_nome  10000 non-null  object
 4   idade          10000 non-null  int64
 5   sexo           10000 non-null  object
 6   raca_cor       10000 non-null  object
 7   escolaridade   10000 non-null  object
 8   peso           10000 non-null  float64
 9   altura         10000 non-null  float64
 10  imc            10000 non-null  float64
dtypes: float64(3), int64(3), object(5)
memory usage: 859.5+ KB

In [86]:
df['ano'].unique()

array([2013, 2011, 2019, 2022, 2018, 2016, 2015, 2020, 2021, 2017, 2014,
       2012])

In [87]:
contagem_uf = df["sigla_uf"].value_counts()
print(contagem_uf)

sigla_uf
MT    3060
SC    2282
AM    1592
AL     591
TO     580
GO     490
MS     328
AC     295
AP     217
MA     206
RR     175
SE     117
ES      52
DF      12
RO       3
Name: count, dtype: int64

In [88]:
contagem_estados = df["sigla_uf_nome"].value_counts()

print(contagem_estados)

sigla_uf_nome
Mato Grosso           3060
Santa Catarina        2282
Amazonas              1592
Alagoas                591
Tocantins              580
Goiás                  490
Mato Grosso do Sul     328
Acre                   295
Amapá                  217
Maranhão               206
Roraima                175
Sergipe                117
Espírito Santo          52
Distrito Federal        12
Rondônia                 3
Name: count, dtype: int64

### **04. Análise Exploratória de Dados.**

In [89]:
# Filtrar o DataFrame para o período da pandemia (2018-2023)
df_pandemia = df[(df['ano'] >= 2018) & (df['ano'] <= 2023)]

# Calcular a média e o desvio padrão do IMC para cada estado
analise_imc_estados = df_pandemia.groupby('sigla_uf_nome')['imc'].agg(['mean', 'std']).reset_index()

# Renomear as colunas para melhor compreensão
analise_imc_estados.rename(columns={'mean': 'Media_IMC', 'std': 'Desvio_Padrao_IMC'}, inplace=True)

# Exibir os resultados
print("Média do IMC por Estado:")
print("-----------------------------------------------------")
print(analise_imc_estados)

Média do IMC por Estado:
-----------------------------------------------------
       sigla_uf_nome  Media_IMC  Desvio_Padrao_IMC
0               Acre  22.398847           5.769087
1            Alagoas  24.137299           6.875287
2              Amapá  22.365918           9.285432
3           Amazonas  22.185145           6.143212
4   Distrito Federal  29.367500           5.529766
5     Espírito Santo  21.228269           6.589737
6              Goiás  24.279252           7.983804
7           Maranhão  22.631854           5.969333
8           Rondônia  15.540000           0.939840
9            Roraima  24.377257           4.744826
10    Santa Catarina  20.184632           6.078295
11           Sergipe  21.310208           7.106937

In [90]:
# @title Dividir os participantes em categorias etárias e calcular o IMC médio por faixa.

# Definir faixas etárias com limites claros
bins = [0, 18, 25, 40, 60, float('inf')]  # Faixas etárias
labels = ["0-18", "19-25", "26-40", "41-60", ">60"]

# Atribuir cada participante a uma faixa etária
df["faixa_etaria"] = pd.cut(df["idade"], bins=bins, labels=labels, right=False)

# Calcular o IMC médio por faixa etária
imc_por_faixa = df.groupby("faixa_etaria")["imc"].mean().reset_index()

# Criar o gráfico de barras
fig = px.bar(
    imc_por_faixa,
    x="faixa_etaria",
    y="imc",
    title="IMC Médio por Faixa Etária",
    labels={"faixa_etaria": "Faixa Etária", "imc": "IMC Médio"},
    text="imc"  # Exibir os valores no topo das barras
)

# Ajustar o texto e a aparência das barras
fig.update_traces(texttemplate="%{text:.2f}", textposition="outside")  # Formatando o texto com 2 casas decimais
fig.update_layout(
    xaxis_title="Faixa Etária",
    yaxis_title="IMC Médio",
    showlegend=False  # Remover a legenda (não necessária)
)

fig.show()

<ipython-input-90-82556d2690f9>:11: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

In [91]:
df.head()

,ano,mes,sigla_uf,sigla_uf_nome,idade,sexo,raca_cor,escolaridade,peso,altura,imc,faixa_etaria
0,2013,8,AP,Amapá,30,F,Parda,Ensino fundamental 5ª a 8ª séries,75.7,1.65,27.81,26-40
1,2013,8,AP,Amapá,2,F,Parda,Creche,9.2,75.00,16.36,0-18
2,2013,8,AP,Amapá,3,M,Parda,Nenhum,15.6,100.00,15.60,0-18
3,2013,8,AP,Amapá,3,F,Branca,Creche,13.9,88.00,17.95,0-18
4,2013,8,AP,Amapá,4,M,Branca,Ensino fundamental 5ª a 8ª séries,19.1,105.00,17.32,0-18

In [92]:
# Calculate the correlation matrix for numerical variables
df_num = df.select_dtypes(include=['float64', 'int64'])


# Display the correlation matrix
print(df_num)

       ano  mes  idade  peso  altura    imc
0     2013    8     30  75.7    1.65  27.81
1     2013    8      2   9.2   75.00  16.36
2     2013    8      3  15.6  100.00  15.60
3     2013    8      3  13.9   88.00  17.95
4     2013    8      4  19.1  105.00  17.32
...    ...  ...    ...   ...     ...    ...
9995  2014   10      3  12.4   90.00  15.31
9996  2014   10      5  18.7  115.00  14.14
9997  2014   10      5  18.2  112.00  14.51
9998  2014   10      6  21.1  114.00  16.24
9999  2014   10      7  22.8    1.27  14.14

[10000 rows x 6 columns]

In [93]:
df.head()

,ano,mes,sigla_uf,sigla_uf_nome,idade,sexo,raca_cor,escolaridade,peso,altura,imc,faixa_etaria
0,2013,8,AP,Amapá,30,F,Parda,Ensino fundamental 5ª a 8ª séries,75.7,1.65,27.81,26-40
1,2013,8,AP,Amapá,2,F,Parda,Creche,9.2,75.00,16.36,0-18
2,2013,8,AP,Amapá,3,M,Parda,Nenhum,15.6,100.00,15.60,0-18
3,2013,8,AP,Amapá,3,F,Branca,Creche,13.9,88.00,17.95,0-18
4,2013,8,AP,Amapá,4,M,Branca,Ensino fundamental 5ª a 8ª séries,19.1,105.00,17.32,0-18

In [95]:
# @title correlação com vairáveis categóricas

# Selecionar apenas as variáveis categóricas
df_cat = df.select_dtypes(include=['object', 'category'])

# Inicializar uma matriz de correlação vazia
corr_matrix = pd.DataFrame(index=df_cat.columns, columns=df_cat.columns)

In [94]:
pip install association-metrics

Requirement already satisfied: association-metrics in /usr/local/lib/python3.11/dist-packages (0.0.1)

# Trabalhos Futuros

---

Calcular / prever

pra dar entrada minha idade, meu município e ver se eu estou na média da minha cidade para minha idade

e tentar prever o IMC do futuro.


regressão usando o IMC como variável base

Usaremos regressão para que, a partir das informações (sexo,idade e localidade e IMC) do usuário nosso sistema perguntará para quanto tempo o usuário quer prever seu imc. O nosso sistema retornará o IMC previsto para aquela localidade, aquela idade e aquele gênero, e verifica a diferença de valores entre o IMC inserido pelo usuário e o IMC previsto pelo modelo

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ano            10000 non-null  int64
 1   mes            10000 non-null  int64
 2   sigla_uf       10000 non-null  object
 3   sigla_uf_nome  10000 non-null  object
 4   idade          10000 non-null  int64
 5   sexo           10000 non-null  object
 6   raca_cor       10000 non-null  object
 7   escolaridade   10000 non-null  object
 8   peso           10000 non-null  float64
 9   altura         10000 non-null  float64
 10  imc            10000 non-null  float64
 11  faixa_etaria   10000 non-null  category
dtypes: category(1), float64(3), int64(3), object(5)
memory usage: 869.5+ KB

In [99]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ano            10000 non-null  int64
 1   mes            10000 non-null  int64
 2   sigla_uf       10000 non-null  object
 3   sigla_uf_nome  10000 non-null  object
 4   idade          10000 non-null  int64
 5   sexo           10000 non-null  object
 6   raca_cor       10000 non-null  object
 7   escolaridade   10000 non-null  object
 8   peso           10000 non-null  float64
 9   altura         10000 non-null  float64
 10  imc            10000 non-null  float64
 11  faixa_etaria   10000 non-null  category
dtypes: category(1), float64(3), int64(3), object(5)
memory usage: 869.5+ KB

---

Após treinar o modelo, é importante validar sua performance com métricas adequadas (como RMSE, R², ou MAE) para garantir que o modelo esteja bem ajustado e generalizando bem para novos dados.

In [100]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

X = df[['idade', 'sexo', 'peso', 'altura', 'escolaridade', 'sigla_uf', 'raca_cor']]  # Variáveis independentes
y = df['imc']  # Variável dependente

# convertendo variável categórica 'sexo' para numérica
X['sexo'] = LabelEncoder().fit_transform(X['sexo'])

<ipython-input-100-f106f5e0a0ca>:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [52]:
X

,idade,sexo,peso,altura,escolaridade,sigla_uf,raca_cor
0,30,0,75.7,1.65,Ensino fundamental 5ª a 8ª séries,AP,Parda
1,2,0,9.2,75.00,Creche,AP,Parda
2,3,1,15.6,100.00,Nenhum,AP,Parda
3,3,0,13.9,88.00,Creche,AP,Branca
4,4,1,19.1,105.00,Ensino fundamental 5ª a 8ª séries,AP,Branca
...,...,...,...,...,...,...,...
9995,3,0,12.4,90.00,Sem informação,GO,Parda
9996,5,1,18.7,115.00,Creche,GO,Branca
9997,5,0,18.2,112.00,Pré-escola (exceto ca),GO,Parda
9998,6,1,21.1,114.00,Pré-escola (exceto ca),GO,Branca
9999,7,0,22.8,1.27,Creche,GO,Parda

In [53]:
from sklearn.model_selection import train_test_split

# Normalizar os dados numéricos
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

ValueError: could not convert string to float: 'Ensino fundamental 5ª a 8ª séries'

In [54]:
X_scaled

NameError: name 'X_scaled' is not defined

In [55]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Dividir em treino (80%) e teste (20%)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

results = {}

NameError: name 'X_scaled' is not defined

In [56]:
from sklearn.ensemble import RandomForestRegressor


# Criar e treinar o modelo Random Forest
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Fazer previsões
y_pred_rf = rf_model.predict(X_test)
results['Random Forest'] = {
    "MAE": mean_absolute_error(y_test, y_pred_rf),
    "RMSE": mean_squared_error(y_test, y_pred_rf),
    "R²": r2_score(y_test, y_pred_rf)
}

NameError: name 'X_train' is not defined

In [ ]:
from sklearn.linear_model import LinearRegression

# Criar e treinar o modelo de regressão linear
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

# Fazer previsões
y_pred_lr = lr_model.predict(X_test)

results['Regressão Linear'] = {
    "MAE": mean_absolute_error(y_test, y_pred_lr),
    "RMSE": mean_squared_error(y_test, y_pred_lr),
    "R²": r2_score(y_test, y_pred_lr)
}

In [ ]:
from sklearn.svm import SVR

# Criar e treinar o modelo de SVR
svr_model = SVR(kernel='rbf')
svr_model.fit(X_train, y_train)

# Fazer previsões
y_pred_svr = svr_model.predict(X_test)

results['SVR'] = {
    "MAE": mean_absolute_error(y_test, y_pred_svr),
    "RMSE": mean_squared_error(y_test, y_pred_svr),
    "R²": r2_score(y_test, y_pred_svr)
}

In [ ]:
from sklearn.ensemble import AdaBoostRegressor

# Criar o modelo AdaBoostRegressor com uma árvore de decisão como modelo base
ada_model = AdaBoostRegressor(n_estimators=100, random_state=42)

# Treinar o modelo
ada_model.fit(X_train, y_train)

# Previsões
y_pred_ada = ada_model.predict(X_test)

results['Regressão Ada'] = {
    "MAE": mean_absolute_error(y_test, y_pred_ada),
    "RMSE": mean_squared_error(y_test, y_pred_ada),
    "R²": r2_score(y_test, y_pred_ada)
}

In [ ]:
df_results = pd.DataFrame(results).T
print(df_results)

                       MAE        RMSE        R²
Random Forest     0.495105   25.427832  0.876452
Regressão Linear  3.808974  154.997246  0.246901
SVR               1.851204  139.780023  0.320838
Regressão Ada     6.055366   81.551435  0.603759

Melhorando o modelo random forest

In [ ]:
df.sample(2)

,ano,mes,sigla_uf,sigla_uf_nome,acompanhamento,id_individuo,idade,sexo,raca_cor,povo_comunidade,escolaridade,data_acompanhamento,peso,altura,imc,periodo,faixa_etaria
1223,2015,10,MT,Mato Grosso,055D9C4624E2A73B871993B7D2A5A9D006141612,D8F5D974554741061428D73A9DC7E49C7165282A,15,F,Parda,Outros,Ensino fundamental completo,2015-10-10,42.0,1.53,17.94,2015-10,0-18
6712,2019,7,MA,Maranhão,460258540804F947B85F1891D55A2FC0A4DC3730,9C01ABFB1ABA0EF386C18398476D6A93B6FA4078,44,F,Branca,Outros,Ensino fundamental 1ª a 4ª séries,2019-07-24,66.0,158.00,26.40,2019-7,41-60

###Melhoramos o modelo com a inserssão de mais duas variáveis: 'raca_cor' e 'escolaridade'

In [57]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

X = df[['idade', 'sexo', 'peso', 'altura', 'escolaridade', 'sigla_uf', 'raca_cor']]  # Variáveis independentes
y = df['imc']  # Variável dependente

# convertendo variável categórica 'sexo' para numérica
X['sexo'] = LabelEncoder().fit_transform(X['sexo'])
X['raca_cor'] = LabelEncoder().fit_transform(X['raca_cor'])
X['escolaridade'] = LabelEncoder().fit_transform(X['escolaridade'])
X['sigla_uf'] = LabelEncoder().fit_transform(X['sigla_uf'])

<ipython-input-57-de0da4c8f827>:7: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-57-de0da4c8f827>:8: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-57-de0da4c8f827>:9: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

<ipython-input-57-de0da4c8f827>:10: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [58]:
# Normalizar os dados numéricos
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [59]:
X_scaled

array([[ 0.4115292 , -0.75016277,  1.12054901, ..., -0.51446602,
        -1.14366856,  0.71191558],
       [-0.9769461 , -0.75016277, -1.35367386, ..., -0.92934125,
        -1.14366856,  0.71191558],
       [-0.9273577 ,  1.33304403, -1.11555316, ...,  1.14503488,
        -1.14366856,  0.71191558],
       ...,
       [-0.82818089, -0.75016277, -1.01881663, ...,  1.3524725 ,
        -0.43272664,  0.71191558],
       [-0.77859249,  1.33304403, -0.91091818, ...,  1.3524725 ,
        -0.43272664, -1.06254998],
       [-0.72900408, -0.75016277, -0.84766737, ..., -0.92934125,
        -0.43272664,  0.71191558]])

In [60]:
# Dividir em treino (80%) e teste (20%)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

results = {}

In [61]:
# Criar e treinar o modelo Random Forest
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Fazer previsões
y_pred_rf = rf_model.predict(X_test)
results['Random Forest'] = {
    "MAE": mean_absolute_error(y_test, y_pred_rf),
    "RMSE": mean_squared_error(y_test, y_pred_rf),
    "R²": r2_score(y_test, y_pred_rf)
}

In [62]:
df_results = pd.DataFrame(results).T
print(df_results)

                    MAE       RMSE        R²
Random Forest  0.564254  25.243885  0.877345

Aplicando a coluna "sigla_uf"

In [63]:
df['sigla_uf'] = LabelEncoder().fit_transform(df['sigla_uf'])

X = df[['idade', 'sexo', 'peso', 'altura', 'escolaridade', 'sigla_uf', 'raca_cor']]
y = df['imc']

In [64]:
import pickle

with open('modelo_random_forest.pkl', 'wb') as file:
    pickle.dump(rf_model, file)

In [65]:
pip install gradio

Collecting gradio
  Downloading gradio-5.15.0-py3-none-any.whl.metadata (16 kB)
Collecting aiofiles<24.0,>=22.0 (from gradio)
  Downloading aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.7.1)
Collecting fastapi<1.0,>=0.115.2 (from gradio)
  Downloading fastapi-0.115.8-py3-none-any.whl.metadata (27 kB)
Collecting ffmpy (from gradio)
  Downloading ffmpy-0.5.0-py3-none-any.whl.metadata (3.0 kB)
Collecting gradio-client==1.7.0 (from gradio)
  Downloading gradio_client-1.7.0-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub>=0.28.1 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.1.5)
Collecting markupsafe~=2.0 (from gradio)
  Downloading MarkupSafe-2.1.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (1.26.4)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (3.10.15)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from gradio) (24.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (11.1.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (2.10.6)
Collecting pydub (from gradio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart>=0.0.18 (from gradio)
  Downloading python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (6.0.2)
Collecting ruff>=0.9.3 (from gradio)
  Downloading ruff-0.9.5-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (25 kB)
Collecting safehttpx<0.2.0,>=0.1.6 (from gradio)
  Downloading safehttpx-0.1.6-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<1.0,>=0.40.0 (from gradio)
  Downloading starlette-0.45.3-py3-none-any.whl.metadata (6.3 kB)
Collecting tomlkit<0.14.0,>=0.12.0 (from gradio)
  Downloading tomlkit-0.13.2-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.11/dist-packages (from gradio) (0.15.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.11/dist-packages (from gradio) (4.12.2)
Collecting uvicorn>=0.14.0 (from gradio)
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.7.0->gradio) (2024.10.0)
Requirement already satisfied: websockets<15.0,>=10.0 in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.7.0->gradio) (14.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.24.1->gradio) (1.0.7)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (3.17.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.28.1->gradio) (4.67.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3.0,>=1.0->gradio) (2025.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.0->gradio) (2.27.2)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (8.1.8)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.28.1->gradio) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.28.1->gradio) (2.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Downloading gradio-5.15.0-py3-none-any.whl (57.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.8/57.8 MB 10.0 MB/s eta 0:00:00
Downloading gradio_client-1.7.0-py3-none-any.whl (321 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 321.9/321.9 kB 29.1 MB/s eta 0:00:00
Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
Downloading fastapi-0.115.8-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.8/94.8 kB 10.1 MB/s eta 0:00:00
Downloading MarkupSafe-2.1.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28 kB)
Downloading python_multipart-0.0.20-py3-none-any.whl (24 kB)
Downloading ruff-0.9.5-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 100.1 MB/s eta 0:00:00
Downloading safehttpx-0.1.6-py3-none-any.whl (8.7 kB)
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading starlette-0.45.3-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 kB 7.8 MB/s eta 0:00:00
Downloading tomlkit-0.13.2-py3-none-any.whl (37 kB)
Downloading uvicorn-0.34.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 6.5 MB/s eta 0:00:00
Downloading ffmpy-0.5.0-py3-none-any.whl (6.0 kB)
Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Installing collected packages: pydub, uvicorn, tomlkit, semantic-version, ruff, python-multipart, markupsafe, ffmpy, aiofiles, starlette, safehttpx, gradio-client, fastapi, gradio
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 3.0.2
    Uninstalling MarkupSafe-3.0.2:
      Successfully uninstalled MarkupSafe-3.0.2
Successfully installed aiofiles-23.2.1 fastapi-0.115.8 ffmpy-0.5.0 gradio-5.15.0 gradio-client-1.7.0 markupsafe-2.1.5 pydub-0.25.1 python-multipart-0.0.20 ruff-0.9.5 safehttpx-0.1.6 semantic-version-2.10.0 starlette-0.45.3 tomlkit-0.13.2 uvicorn-0.34.0

In [66]:
import gradio as gr

In [67]:
import joblib  # Para carregar o modelo treinado

In [68]:
rf_model = joblib.load("modelo_random_forest.pkl")

In [69]:
def processar_dados(dados):
  dados ['sexo'] = LabelEncoder().fit_transform(X['sexo'])
  dados ['raca_cor'] = LabelEncoder().fit_transform(X['raca_cor'])
  dados ['escolaridade'] = LabelEncoder().fit_transform(X['escolaridade'])
  dados ['sigla_uf'] = LabelEncoder().fit_transform(X['sigla_uf'])
  # Normalizar os dados numéricos
  scaler = StandardScaler()
  X_scaled = scaler.fit_transform(dados)
  return X_scaled

In [70]:
def prever_imc(idade, sexo, peso, altura, escolaridade, estado, raca):
    # Criar um DataFrame com os inputs do usuário
    dados = pd.DataFrame([[idade, sexo, peso, altura, escolaridade, estado, raca]],
                         columns=["idade", "sexo", "peso", "altura", "escolaridade", "sigla_uf", "raça"])

    # Pré-processamento dos dados (exemplo: transformar categóricos em numéricos)
    dados = processar_dados(dados)  # Certifique-se de ter essa função implementada como no seu treinamento

    # Fazer a previsão
    imc_previsto = rf_model.predict(dados)

    return f"IMC Previsto: {imc_previsto[0]:.2f}"

In [71]:
# Criar a interface com Gradio
interface = gr.Interface(
    fn=prever_imc,  # Função de previsão
    inputs=[
        gr.Number(label="Idade"),
        gr.Radio(["Masculino", "Feminino"], label="Sexo"),
        gr.Number(label="Peso (kg)"),
        gr.Number(label="Altura (cm)"),
        gr.Dropdown(["Ensino Fundamental", "Ensino Médio", "Superior", "Pós-graduação"], label="Escolaridade"),
        gr.Number(label="Estado)"),
        gr.Dropdown(["Branco", "Negro", "Pardo", "Indígena", "Amarelo"], label="Raça")
    ],
    outputs="text",
    title="Previsão de IMC com Random Forest",
    description="Digite as informações abaixo para prever o Índice de Massa Corporal (IMC) com base no modelo Random Forest."
)

# Iniciar a interface
interface.launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://7749d0b1be33c3778f.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [ ]:
df

,ano,mes,sigla_uf,sigla_uf_nome,idade,sexo,raca_cor,escolaridade,peso,altura,imc,imc_gestacional
0,2013,8,3,Amapá,30,F,Parda,Ensino fundamental 5ª a 8ª séries,75.7,1.65,27.81,NaN
1,2013,8,3,Amapá,2,F,Parda,Creche,9.2,75.00,16.36,NaN
2,2013,8,3,Amapá,3,M,Parda,Nenhum,15.6,100.00,15.60,NaN
3,2013,8,3,Amapá,3,F,Branca,Creche,13.9,88.00,17.95,NaN
4,2013,8,3,Amapá,4,M,Branca,Ensino fundamental 5ª a 8ª séries,19.1,105.00,17.32,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2014,10,6,Goiás,3,F,Parda,Sem informação,12.4,90.00,15.31,NaN
9996,2014,10,6,Goiás,5,M,Branca,Creche,18.7,115.00,14.14,NaN
9997,2014,10,6,Goiás,5,F,Parda,Pré-escola (exceto ca),18.2,112.00,14.51,NaN
9998,2014,10,6,Goiás,6,M,Branca,Pré-escola (exceto ca),21.1,114.00,16.24,NaN
9999,2014,10,6,Goiás,7,F,Parda,Creche,22.8,1.27,14.14,NaN