***
# <font color=green size=10>**DS-002 - GERENCIAMENTO DE DADOS PARA ANÁLISE - AULA 01**</font>
***

**1. Pergunta orientadora:** Quais conjuntos de atributos se associam ao elevado número de casos de dengue no Brasil?

**2. Experiência da disciplina:** Obtenção de base de dados no Kaggle sobre Dengue, pré-processamento e análise exploratória de dados.

**3. Base de Dados que utilizaremos:**
[Link-Dados-Dengue-Brasil](https://www.kaggle.com/datasets/jimmyyyyyyy/dengue-in-brazil-2012-2021?select=State_Dengue_Model_Data_w_pop.csv). Apesar deste link, utilize a base que está no Moodle.

## <font color=green size=6>**01. LEMBRETES IMPORTANTES**</font>

In [98]:
########################
### ALGUNS LEMBRETES ###
########################

# Este arquivo aqui no qual você está é chamado de notebook.

# Este texto aqui é um comentário.
# Ele sempre aparecerá nessa tonalidade de verde.

# O Python sabe identificar um comentário porque colocamos antes do texto o
# símbolo '#'.

# Notebooks são organizados em 2 tipos de "células":
# (1) Texto (ex.: campo acima) e (2) Código (ex. esta aqui).

# Veja um exemplo de código a seguir:

nome = input("Qual é o seu primeiro nome? Resposta: ")
resposta = input("Este é o seu 1º curso de Ciência de Dados? Se sim, escreva s. Para não, n. Resposta: ")
if resposta == 's':
    print(f"Muito prazer, ", nome,
          "! Bom contar contigo nesta disciplina, que é a sua primeira experiência com Ciência de Dados :)")
else:
    print(f"Muito prazer, ", nome, "! Bom contar contigo nesta disciplina :)")

# Para executar o código, acione as teclas "CTRL + ENTER" ou
# use o botão "Run", com o símbolo de 'Play'.

# Note que, após a execução do código, nenhum comentário foi exibido abaixo.

# Atenção: não se esqueça de que códigos devem ser organizados como
# sequências de comandos.

KeyboardInterrupt: Interrupted by user

## <font color=green size=6>**02. PREPARANDO O AMBIENTE DE TRABALHO**</font>

🤓 **Hoje, usaremos uma sequência de comandos que nos permitirá analisar dados com Python.**

* O nosso primeiro passo será fazer o download de uma base de dados sobre casos de dengue no Brasil. O link é o mesmo que está na primeira célula: [Link-Dados-Dengue-Brasil](https://www.kaggle.com/datasets/jimmyyyyyyy/dengue-in-brazil-2012-2021?select=State_Dengue_Model_Data_w_pop.csv). Apesar deste link, utilize a base que está no Moodle.

**Siga os passos a seguir:**

1. Caso esteja no Google Colab, faça upload da base de dados. Na sequência, obtenha o caminho do arquivo. Ao passar o cursor sobre o arquivo, você verá três pontinhos na vertical, logo na direta do arquivo selecionado. Clique neles e, então, você verá a opção de `Copiar caminho`. Veha a imagem abaixo.

![](https://cdn1.gnarususercontent.com.br/1/547588/9fc47f1b-b54c-4b42-a6e3-a14d3d917ccd.png)

2. Se estiver no Jupyter Notebook, salve o arquivo *.csv no local que desejar, na máquina em que estiver trabalhando. Copie o caminho do arquivo. Veja o exemplo abaixo.

![](https://www.wikihow.com/images/thumb/5/51/Find-a-File%27s-Path-on-Windows-Step-5.jpg/v4-728px-Find-a-File%27s-Path-on-Windows-Step-5.jpg.webp)

*Esta imagem de exemplo é de um site que ensina como obter esse caminho.*
*Acesse o link abaixo, caso precise de mais ajuda.*

[Link-WikiHow-Caminho-Arquivo-Windows](https://pt.wikihow.com/Encontrar-o-Caminho-de-um-Arquivo-no-Windows)

## <font color=green size=6>**03. PRÉ-PROCESSAMENTO**</font>

##### **01. Importe a biblioteca Pandas. Ela possui códigos prontos, para que possamos abrir com o Python a base de dados.**

Padrão dominante para aplicações Python orientadas a dados. Possui duas estruturas de dados: *Series*, que trabalha com informações em 1 Dimensão, e *DataFrame*, que possui 2 Dimensões. Na prática, o DataFrame é uma coleção de objetos Series.

*Neste [vídeo](https://www.youtube.com/watch?v=yCtiqMRt4TQ), vemos uma síntese sobre o que é e qual o grau de importância do Pandas.*

> O `pd` é um apelido curto, para que possamos nos referir a esta biblioteca e usar os seus recursos em nosso código.

In [ ]:
import pandas as pd

##### **02. Obtenha a base de dados.**
> O `r` antes do caminho do arquivo garante que todos os caracteres desse caminho sejam interpretados como texto. Na ausência dele, a barra invertida é interpretada como caractere de escape, cuja ação depende da próxima letra. Por exemplo: `\n` leva o Python a pular uma linha.

In [ ]:
dados = pd.read_csv(r'/content/dengue.csv')

##### **03. Verifique o conteúdo da base de dados, para estar seguro de que os dados foram obtidos adequadamente.**
> Podemos ter uma noção do conteúdo do banco, pedindo para o Python nos mostrar os seus 5 primeiros registros por meio do atributo `.head()`.

In [ ]:
dados.head()

> Podemos ter uma ideia dos últimos 5 itens do nosso banco, pedindo isso ao Python com o seguinte comando.

In [ ]:
dados.tail()

**Informações importantes sobre a base de dados:**

🤔**O que signica cada coluna:**

- Year: ano entre 2012 e 2021
- State: estado brasileiro
- Mean_Tmp: temperatura média em graus Celsius no ano
- Min_Tmp: temperatura mínima em graus Celsius no ano
- Max_Tmp: temperatura máxima em graus Celsius no ano
- Percipitation: precipitação anual em milímetros
- Change_Tmp: temp. máx. anual menos temp. mín. anual em graus Celsius
- State_ID: número de identificação do estado brasileiro
- Cases: número de casos de dengue
- Region: região brasileira (Norte = N, Nordeste = NE, Centro-Oeste = CO, Sudeste = SE, Sul = S)
- State_Area(km2): área em km2 do estado
- Population: estimativa da população total

💻**Como o Pandas guarda os nossos dados:**

- O pandas armazena o nosso banco como um `DataFrame`, que é uma estrutura bi-dimensional, que pode contar diversos tipos de dados, sendo os elementos rotulados.
- Os rótulos das linhas estão no atributo *index*, que são os números de 0 em diante que podem ser vistos acima, na extrema esquerda da tabela. Já os rótulos de colunas ficam no atributo *columns*.
- Daqui em diante, vamos usar o termo `DataFrame` como substiuto de banco de dados.

##### **04. Crie uma cópia do DataFrame original.**
> Esta é uma boa prática, para evitarmos o risco de perder ou modificar algo da base original. Nessa cópia, é útil deixar apenas as variáveis que iremos analisar.

In [ ]:
df_dengue = pd.DataFrame(dados, columns = ['Year', 'State', 'Population', 'Region', 'Min_Tmp',
                                               'Max_Tmp', 'Change_Tmp', 'Mean_Tmp', 'Percipitation','Cases'])

##### **05. Consulte o banco copiado, para verificar se está correto.**

In [ ]:
df_dengue.head()

##### **06. Verifique quais são os estados que estão presentes no banco de dados.**

In [ ]:
df_dengue['State']

In [ ]:
df_dengue['State'].unique()

##### **07. Descubra os casos de NaN e NULL na base de dados.**

> Podem ocorrer casos de valores que não são números e de valores nulos. A depender de casa situação, pode ser necessário remover ambos. É o que faremos aqui.

In [ ]:
# Casos de valores ausentes
df_dengue.isnull().any()

In [ ]:
# Casos de valores ausentes
# Exibição das linhas
df_dengue[df_dengue.isnull().any(axis=1)]

In [ ]:
# Casos de valores que não são números
df_dengue.isna().any()

In [ ]:
# Casos de valores que não são números
# Exibição das linhas
df_dengue[df_dengue.isna().any(axis=1)]

##### **08. Remova todos os casos de NaN do banco de dados.**

In [ ]:
df_dengue = df_dengue.dropna()

##### **09. Verifique se ainda existem casos de NaN e avalie como ficou a base de dados.**

In [ ]:
df_dengue[df_dengue.isna().any(axis=1)]

In [ ]:
df_dengue.tail()

💰**Bônus:**
> Se você quisesse, poderia mudar os nomes das colunas do seu DataFrame. Para isso, basta usar o método `.rename()`.

##### **10. Inspecione algumas características do seu DataFrame.**

In [ ]:
df_dengue.info()

##### **11. Verifique o tamanho do seu DataFrame.**

In [ ]:
df_dengue.shape

##### **12. Crie uma nova coluna chamada SeveralCases, que irá conter apenas dois valores: 0, quando o número de casos em uma linha estiver abaixo da mediana do conjunto de dados e 1, quando for maior.**

In [ ]:
mediana = df_dengue['Cases'].median()
print("A mediana é igual a ", mediana)

In [ ]:
def ident_se_muitos_casos(casos):
  if casos > mediana:
    return 1
  else:
    return 0

df_dengue['SeveralCases'] = df_dengue['Cases'].apply(ident_se_muitos_casos)

##### **13. Consulte o DataFrame para examinar se a coluna foi criada.**

In [ ]:
df_dengue

##### **14. Verifique com quantos valores de cada classe (1 e 0) da coluna SeveralCases o seu DataFrame ficou.**

In [ ]:
df_dengue['SeveralCases'].value_counts(normalize=False)

***
# <font color=green size=10>**DS-002 - GERENCIAMENTO DE DADOS PARA ANÁLISE - AULA 02**</font>
***

In [158]:
# @title Reiniciando o notebook
import pandas as pd

dados = pd.read_csv('/content/drive/MyDrive/Ciência da Computação/Data Science - Projeto de Extensão/DS-002 - Gerenciamento de Dados para Análise/Aula 02/dengue.csv')

df_dengue = pd.DataFrame(dados, columns = ['Year', 'State', 'Population', 'Region', 'Min_Tmp',
                                               'Max_Tmp', 'Change_Tmp', 'Mean_Tmp', 'Percipitation','Cases'])
df_dengue = df_dengue.dropna()

mediana = df_dengue['Cases'].median()
def ident_se_muitos_casos(casos):
  if casos > mediana:
    return 1
  else:
    return 0

df_dengue['SeveralCases'] = df_dengue['Cases'].apply(ident_se_muitos_casos)

##### **15. Crie uma nova coluna chamada FromMainStates para sabermos quais são as linhas do banco relativas ao estados que se destacam em relação à quantidade de casos de dengue: Distrito Federal, Minas Gerais e Paraná.**

In [159]:
# Criar a coluna 'FromMainStates'
main_states = ['Distrito Federal', 'Minas Gerais', 'Paraná']
df_dengue['FromMainStates'] = df_dengue['State'].apply(lambda x: 1 if x in main_states else 0)

##### **16. Consulte o banco para verificar se esta coluna foi criada.**

In [160]:
# Consultar o banco para verificar se a coluna 'FromMainStates' foi criada
df_dengue.head()

,Year,State,Population,Region,Min_Tmp,Max_Tmp,Change_Tmp,Mean_Tmp,Percipitation,Cases,SeveralCases,FromMainStates
0,2012,Acre,758786,N,20.48,31.05,10.57,25.74,1851.90,22,0,0
1,2013,Acre,776463,N,20.40,30.86,10.46,25.61,1909.14,9229,0,0
2,2014,Acre,790101,N,20.57,31.04,10.47,25.78,2243.00,36795,1,0
3,2015,Acre,803513,N,20.88,31.62,10.74,26.22,1895.83,14320,1,0
4,2016,Acre,816687,N,20.66,31.71,11.05,26.16,1874.84,9237,0,0

##### **17. Pesquise por todos os valores iguais a `Parana` para ver se, na última coluna, estão relacionados ao número 3.**

In [161]:
# Pesquisar por todos os valores iguais a 'Paraná' na coluna 'State'
parana_rows = df_dengue[df_dengue['State'] == 'Parana']
print(parana_rows)

     Year   State  Population Region  Min_Tmp  Max_Tmp  Change_Tmp  Mean_Tmp  \
145  2012  Parana    10577755      S    14.70    26.06       11.36     20.36
146  2013  Parana    10997465      S    14.13    25.16       11.03     19.62
147  2014  Parana    11081692      S    15.22    26.04       10.82     20.60
148  2015  Parana    11163018      S    15.40    25.82       10.42     20.59
149  2016  Parana    11242720      S    14.39    25.45       11.06     19.90
150  2017  Parana    11320892      S    15.12    25.95       10.83     20.51
151  2018  Parana    11348937      S    14.79    25.81       11.02     20.27
152  2019  Parana    11433957      S    15.35    26.43       11.08     20.86
153  2020  Parana    11516840      S    14.64    26.49       11.85     20.54
154  2021  Parana    11597484      S    14.46    26.04       11.58     20.22

     Percipitation   Cases  SeveralCases  FromMainStates
145        1524.60      46             0               0
146        1759.23  112356             1               0
147        1857.12   56231             1               0
148        2146.55   97930             1               0
149        1672.82  135965             1               0
150        1711.97   26958             1               0
151        1372.67   17962             1               0
152        1410.93  113510             1               0
153        1234.75  359115             1               0
154        1190.36     128             0               0

##### **18. Conte quantas vezes `Parana` aparece no DataFrame.**

In [162]:
# Contar quantas vezes 'Paraná' aparece na coluna 'State'
count_parana = df_dengue[df_dengue['State'] == 'Parana'].shape[0]
print("Número de vezes que 'Paraná' aparece:", count_parana)

Número de vezes que 'Paraná' aparece: 10

##### **19. Pesquise por todos os valores iguais a 3 na coluna que criamos.**

> É sempre bom ter certeza de que não fizemos nada de errado. Portanto, utilizar diferentes estratégias para examinar os dados é importante.

In [163]:
# Pesquisar por todos os valores iguais a 3 na coluna 'FromMainStates'
main_states_rows = df_dengue[df_dengue['FromMainStates'] == 1]
print(main_states_rows)

     Year             State  Population Region  Min_Tmp  Max_Tmp  Change_Tmp  \
58   2012  Distrito Federal     2648532     CO    17.19    28.08       10.89
59   2013  Distrito Federal     2789761     CO    17.28    27.95       10.67
60   2014  Distrito Federal     2852372     CO    17.34    28.38       11.04
61   2015  Distrito Federal     2914830     CO    17.52    28.69       11.17
62   2016  Distrito Federal     2977216     CO    17.62    28.89       11.27
63   2017  Distrito Federal     3039444     CO    17.45    28.32       10.87
64   2018  Distrito Federal     2974703     CO    17.38    28.13       10.75
65   2019  Distrito Federal     3015268     CO    17.77    28.95       11.18
66   2020  Distrito Federal     3055149     CO    17.55    28.31       10.76
67   2021  Distrito Federal     3094325     CO    17.15    28.25       11.10
116  2012      Minas Gerais    19855332     SE    16.78    28.89       12.11
117  2013      Minas Gerais    20593356     SE    16.84    28.50       11.66
118  2014      Minas Gerais    20734097     SE    16.81    29.34       12.53
119  2015      Minas Gerais    20869101     SE    17.28    29.57       12.29
120  2016      Minas Gerais    20997560     SE    17.05    29.49       12.44
121  2017      Minas Gerais    21119536     SE    16.87    29.01       12.14
122  2018      Minas Gerais    21040662     SE    16.99    28.90       11.91
123  2019      Minas Gerais    21168791     SE    17.28    29.76       12.48
124  2020      Minas Gerais    21292666     SE    16.98    29.09       12.11
125  2021      Minas Gerais    21411923     SE    16.53    28.96       12.43

     Mean_Tmp  Percipitation   Cases  SeveralCases  FromMainStates
58      22.61        1271.50       2             0               1
59      22.59        1639.04   26590             1               1
60      22.83        1342.83   20073             1               1
61      23.08        1204.36   12981             1               1
62      23.23        1258.07   24023             1               1
63      22.85        1230.97    6492             0               1
64      22.73        1504.59    4141             0               1
65      23.33        1247.11   46251             1               1
66      22.91        1566.32   64579             1               1
67      22.67        1681.24     108             0               1
116     22.81        1058.29     195             0               1
117     22.65        1380.75  501899             1               1
118     23.05         870.17   93941             1               1
119     23.40        1007.32  258341             1               1
120     23.25        1172.44  666893             1               1
121     22.92         974.72   61532             1               1
122     22.92        1279.00   59362             1               1
123     23.49        1006.37  617296             1               1
124     23.01        1407.40  146813             1               1
125     22.72        1258.82      28             0               1

##### **20. Some todos os valores da coluna FromMainStates, que são iguais a 3, para termos certeza de que não temos mais do que 10 registros iguais a 3.**

In [164]:
# Some todos os valores da coluna FromMainStates, que são iguais a 3, para termos certeza de que não temos mais do que 10 registros iguais a 3.

count_main_states = df_dengue[df_dengue['FromMainStates'] == 1].shape[0]
print("Número de registros com valor 3 na coluna 'FromMainStates':", count_main_states)

Número de registros com valor 3 na coluna 'FromMainStates': 20

##### **21. Crie uma coluna FromNNECOorSSE que irá conter o valor 1 se a linha for das regiões N, NE ou CO e 2 se for das regiões S ou SE e verifique se o DataFrame ficou correto.**

In [165]:
# Criar a coluna 'FromNNECOorSSE'
df_dengue['FromNNECOorSSE'] = df_dengue['Region'].apply(lambda x: 1 if x in ['N', 'NE', 'CO'] else 2)

In [166]:
df_dengue.head()

,Year,State,Population,Region,Min_Tmp,Max_Tmp,Change_Tmp,Mean_Tmp,Percipitation,Cases,SeveralCases,FromMainStates,FromNNECOorSSE
0,2012,Acre,758786,N,20.48,31.05,10.57,25.74,1851.90,22,0,0,1
1,2013,Acre,776463,N,20.40,30.86,10.46,25.61,1909.14,9229,0,0,1
2,2014,Acre,790101,N,20.57,31.04,10.47,25.78,2243.00,36795,1,0,1
3,2015,Acre,803513,N,20.88,31.62,10.74,26.22,1895.83,14320,1,0,1
4,2016,Acre,816687,N,20.66,31.71,11.05,26.16,1874.84,9237,0,0,1

##### **22. Crie uma nova coluna com o cálculo do percentual de casos na população e verifique se o DataFrame ficou correto.**

In [167]:
# Criar a coluna com o cálculo do percentual de casos na população
df_dengue['PercentualCasosPopulacao'] = (df_dengue['Cases'] / df_dengue['Population']) * 100

In [168]:
df_dengue.head()

,Year,State,Population,Region,Min_Tmp,Max_Tmp,Change_Tmp,Mean_Tmp,Percipitation,Cases,SeveralCases,FromMainStates,FromNNECOorSSE,PercentualCasosPopulacao
0,2012,Acre,758786,N,20.48,31.05,10.57,25.74,1851.90,22,0,0,1,0.002899
1,2013,Acre,776463,N,20.40,30.86,10.46,25.61,1909.14,9229,0,0,1,1.188595
2,2014,Acre,790101,N,20.57,31.04,10.47,25.78,2243.00,36795,1,0,1,4.657000
3,2015,Acre,803513,N,20.88,31.62,10.74,26.22,1895.83,14320,1,0,1,1.782174
4,2016,Acre,816687,N,20.66,31.71,11.05,26.16,1874.84,9237,0,0,1,1.131033

💰**Bônus - Identificação dos dados relativos a um valor máximo**

##### **23. Crie um novo DataFrame, após remover a coluna State e verifique se o novo DataFrame ficou conforme o esperado após a exclusão.**

In [169]:
# Crie um novo DataFrame, após remover a coluna State e verifique se o novo DataFrame ficou conforme o esperado após a exclusão.

# Crie um novo DataFrame, após remover a coluna State
df_dengue_sem = df_dengue.drop('State', axis=1)

# Verifique se o novo DataFrame ficou conforme o esperado após a exclusão.
df_dengue_sem.head()

,Year,Population,Region,Min_Tmp,Max_Tmp,Change_Tmp,Mean_Tmp,Percipitation,Cases,SeveralCases,FromMainStates,FromNNECOorSSE,PercentualCasosPopulacao
0,2012,758786,N,20.48,31.05,10.57,25.74,1851.90,22,0,0,1,0.002899
1,2013,776463,N,20.40,30.86,10.46,25.61,1909.14,9229,0,0,1,1.188595
2,2014,790101,N,20.57,31.04,10.47,25.78,2243.00,36795,1,0,1,4.657000
3,2015,803513,N,20.88,31.62,10.74,26.22,1895.83,14320,1,0,1,1.782174
4,2016,816687,N,20.66,31.71,11.05,26.16,1874.84,9237,0,0,1,1.131033

##### **24. Remova a coluna Region e verifique como o DataFrame ficou.**

In [170]:
# Remova a coluna Region e verifique como o DataFrame ficou.

df_dengue_sem = df_dengue_sem.drop('Region', axis=1)

# Verifique como o DataFrame ficou.
df_dengue_sem.head()

,Year,Population,Min_Tmp,Max_Tmp,Change_Tmp,Mean_Tmp,Percipitation,Cases,SeveralCases,FromMainStates,FromNNECOorSSE,PercentualCasosPopulacao
0,2012,758786,20.48,31.05,10.57,25.74,1851.90,22,0,0,1,0.002899
1,2013,776463,20.40,30.86,10.46,25.61,1909.14,9229,0,0,1,1.188595
2,2014,790101,20.57,31.04,10.47,25.78,2243.00,36795,1,0,1,4.657000
3,2015,803513,20.88,31.62,10.74,26.22,1895.83,14320,1,0,1,1.782174
4,2016,816687,20.66,31.71,11.05,26.16,1874.84,9237,0,0,1,1.131033

##### **25. Reordene as colunas de modo que FromMainStates seja a segunda, seguida por FromNNEorSSE, depois Population e, finalmente, pode manter a ordem das demais colunas. Em seguida, verifique se as mudanças de ordem persistiram no DataFrame.**

In [171]:
# Reordene as colunas de modo que FromMainStates seja a segunda, seguida por FromNNEorSSE, depois Population e, finalmente, pode manter a ordem das demais colunas. Em seguida, verifique se as mudanças de ordem persistiram no DataFrame.

# Reordene as colunas
df_dengue_sem = df_dengue_sem[['Year', 'FromMainStates', 'FromNNECOorSSE', 'Population', 'Min_Tmp',
                                               'Max_Tmp', 'Change_Tmp', 'Mean_Tmp', 'Percipitation','Cases', 'SeveralCases', 'PercentualCasosPopulacao']]

# Verifique se as mudanças de ordem persistiram no DataFrame.
df_dengue_sem.head()

,Year,FromMainStates,FromNNECOorSSE,Population,Min_Tmp,Max_Tmp,Change_Tmp,Mean_Tmp,Percipitation,Cases,SeveralCases,PercentualCasosPopulacao
0,2012,0,1,758786,20.48,31.05,10.57,25.74,1851.90,22,0,0.002899
1,2013,0,1,776463,20.40,30.86,10.46,25.61,1909.14,9229,0,1.188595
2,2014,0,1,790101,20.57,31.04,10.47,25.78,2243.00,36795,1,4.657000
3,2015,0,1,803513,20.88,31.62,10.74,26.22,1895.83,14320,1,1.782174
4,2016,0,1,816687,20.66,31.71,11.05,26.16,1874.84,9237,0,1.131033

##### **26. Transforme a coluna Year no index do banco de dados.**

> Fazer isso pode deixar o seu banco de dados mais fácil de interpretar e sem uma coluna com números de índice criada automaticamente pela biblioteca Pandas.

In [172]:
# Transforme a coluna Year no index do banco de dados.

df_dengue_sem = df_dengue_sem.set_index('Year')

In [173]:
df_dengue_sem.head()

,FromMainStates,FromNNECOorSSE,Population,Min_Tmp,Max_Tmp,Change_Tmp,Mean_Tmp,Percipitation,Cases,SeveralCases,PercentualCasosPopulacao
Year,,,,,,,,,,,
2012,0,1,758786,20.48,31.05,10.57,25.74,1851.90,22,0,0.002899
2013,0,1,776463,20.40,30.86,10.46,25.61,1909.14,9229,0,1.188595
2014,0,1,790101,20.57,31.04,10.47,25.78,2243.00,36795,1,4.657000
2015,0,1,803513,20.88,31.62,10.74,26.22,1895.83,14320,1,1.782174
2016,0,1,816687,20.66,31.71,11.05,26.16,1874.84,9237,0,1.131033

##### **27. Crie um novo DataFrame com todos os atributos, exceto a coluna FromNNECOorSSE.**

> Quando trabalhamos com Machine Learning / Aprendizado de Máquina, tipicamente, buscamos classificar ou prever um fenômeno, o nosso **alvo** ou *target* ou *label*, em função de um conjunto de **atributos** ou *features*. Para facilitar o nosso trabalho, é útil separar em dois DataFrames distintos target e features.

In [174]:
# Crie um novo DataFrame com todos os atributos, exceto a coluna FromNNECOorSSE.

df_features = df_dengue_sem.drop(['FromNNECOorSSE'], axis=1)

In [175]:
df_features.head()

,FromMainStates,Population,Min_Tmp,Max_Tmp,Change_Tmp,Mean_Tmp,Percipitation,Cases,SeveralCases,PercentualCasosPopulacao
Year,,,,,,,,,,
2012,0,758786,20.48,31.05,10.57,25.74,1851.90,22,0,0.002899
2013,0,776463,20.40,30.86,10.46,25.61,1909.14,9229,0,1.188595
2014,0,790101,20.57,31.04,10.47,25.78,2243.00,36795,1,4.657000
2015,0,803513,20.88,31.62,10.74,26.22,1895.83,14320,1,1.782174
2016,0,816687,20.66,31.71,11.05,26.16,1874.84,9237,0,1.131033

##### **28. Crie um objeto Series apenas com o nosso target, FromNNECOorSSE.**

> Series é um objeto da biblioteca Pandas que possui apenas uma dimensão.

In [176]:
# Crie um objeto Series apenas com o nosso target, FromNNECOorSSE.

target = df_dengue_sem['FromNNECOorSSE']

In [177]:
target.head()

Year
2012    1
2013    1
2014    1
2015    1
2016    1
Name: FromNNECOorSSE, dtype: int64

##### **29. Transforme os dados da coluna FromMainStates em variáveis dummy.**

> Vários modelos de inteligência artificial, como a Árvore de Decisão, não irão processar valores de texto como os contidos na coluna Region. Felizmente, podemos criar uma coluna para cada região (N, NE, S, SE e CO), que, por exemplo, na coluna da região Norte, conterá o número 1 quando a linha do banco for referente ao Norte e 0, caso contrário.

In [178]:
# Transforme os dados da coluna FromMainStates em variáveis dummy.

import pandas as pd
df_dummies = pd.get_dummies(df_dengue_sem[['FromMainStates']])
df_dummies.head()

      FromMainStates
Year
2012               0
2013               0
2014               0
2015               0
2016               0

##### **30. Mude o nome das novas colunas de features criadas, reordene as colunas para as novas ficarem no início do banco e verifique como ficou o DataFrame `features_encoded` após esse conjunto de mudanças.**

In [179]:
import pandas as pd
# Mude o nome das novas colunas de features criadas
df_dummies = df_dummies.rename(columns={'FromMainStates_0': 'FromMainStates_0_dummy', 'FromMainStates_1': 'FromMainStates_1_dummy'})

# Reordene as colunas para as novas ficarem no início do banco
df_dummies = pd.concat([df_dummies, df_features], axis=1)

# Verifique como ficou o DataFrame features_encoded após esse conjunto de mudanças
df_dummies.head()

,FromMainStates,FromMainStates,Population,Min_Tmp,Max_Tmp,Change_Tmp,Mean_Tmp,Percipitation,Cases,SeveralCases,PercentualCasosPopulacao
Year,,,,,,,,,,,
2012,0,0,758786,20.48,31.05,10.57,25.74,1851.90,22,0,0.002899
2013,0,0,776463,20.40,30.86,10.46,25.61,1909.14,9229,0,1.188595
2014,0,0,790101,20.57,31.04,10.47,25.78,2243.00,36795,1,4.657000
2015,0,0,803513,20.88,31.62,10.74,26.22,1895.83,14320,1,1.782174
2016,0,0,816687,20.66,31.71,11.05,26.16,1874.84,9237,0,1.131033

## <font color=green size=6>**TAREFA 02**</font>
*Esta é a atividade que você fará nas suas horas de aula on-line.*

**1. Usando a base de dados sobre casos de dengue no Brasil, `df_dengue`, crie uma coluna com uma variável categórica baseada no nível de Precipitação. A variável categórica deve ser `HighPercipitation`, contendo 1 para casos de precipitação maiores que a mediana e 0 para casos menores. Entregue o notebook com esta tarefa no Moodle do curso, por meio de um link de compartilhamento.**

In [180]:
# Calculando a mediana da Precipitação
mediana_precipitacao = df_dengue['Percipitation'].median()

In [181]:
# Criando a coluna HighPrecipitation
df_dengue['HighPrecipitation'] = df_dengue['Percipitation'].apply(lambda x: 1 if x > mediana_precipitacao else 0)

In [183]:
# Verificando o DataFrame
df_dengue.head()

,Year,State,Population,Region,Min_Tmp,Max_Tmp,Change_Tmp,Mean_Tmp,Percipitation,Cases,SeveralCases,FromMainStates,FromNNECOorSSE,PercentualCasosPopulacao,HighPrecipitation
0,2012,Acre,758786,N,20.48,31.05,10.57,25.74,1851.90,22,0,0,1,0.002899,1
1,2013,Acre,776463,N,20.40,30.86,10.46,25.61,1909.14,9229,0,0,1,1.188595,1
2,2014,Acre,790101,N,20.57,31.04,10.47,25.78,2243.00,36795,1,0,1,4.657000,1
3,2015,Acre,803513,N,20.88,31.62,10.74,26.22,1895.83,14320,1,0,1,1.782174,1
4,2016,Acre,816687,N,20.66,31.71,11.05,26.16,1874.84,9237,0,0,1,1.131033,1